 CREATE TABLE User (
 userId INT AUTO_INCREMENT PRIMARY KEY,
 userName VARCHAR(25) NOT NULL,
 userEmail VARCHAR(100) NOT NULL,
 userLevel INT DEFAULT 1,
 userExperience INT DEFAULT 0
 );

CREATE TABLE Note (
noteId INT AUTO_INCREMENT PRIMARY KEY,
userId INT,
noteTitle VARCHAR(100) NOT NULL,
noteContent TEXT,
createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (userId) REFERENCES User(userId)
);
