DROP TABLE IF EXISTS Cosmigo;
 DROP TABLE IF EXISTS Todo;
 DROP TABLE IF EXISTS pomodoro;
 DROP TABLE IF EXISTS Note;
 DROP TABLE IF EXISTS User;
 
 CREATE TABLE IF NOT EXISTS User (
    userId INT AUTO_INCREMENT PRIMARY KEY,
    userName VARCHAR(25) NOT NULL,
    userEmail VARCHAR(100) NOT NULL,
    userLevel INT DEFAULT 1,
    userExperience INT DEFAULT 0,
    UNIQUE (userEmail)
 );

CREATE TABLE IF NOT EXISTS Note (
    noteId INT AUTO_INCREMENT PRIMARY KEY,
    userId INT,
    noteTitle VARCHAR(100) NOT NULL,
    noteContent TEXT,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES User(userId)
);
CREATE TABLE IF NOT EXISTS pomodoro (
    pomodoroId INT AUTO_INCREMENT PRIMARY KEY,
    sessionType VARCHAR(50) NOT NULL,
    duration INT NOT NULL,
    completed TINYINT(1) DEFAULT 0,
    startTime DATETIME,
    endTime DATETIME,
    pomodoroUserId INT,
    CONSTRAINT fk_pomodoro_user
    FOREIGN KEY (pomodoroUserId)
    REFERENCES User(userId)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Todo(
    todoId INT AUTO_INCREMENT PRIMARY KEY,
    userId INT NOT NULL,
    todoTitle VARCHAR(100) NOT NULL,
    todoDescription TEXT,
    todoIsCompleted BOOLEAN DEFAULT FALSE,
    todoCreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    todoUpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES User(userId) ON DELETE CASCADE

);

CREATE TABLE IF NOT EXISTS Cosmigo (
    userId INT PRIMARY KEY,
    unlocked JSON NOT NULL,
    equippedKey VARCHAR(100) DEFAULT NULL,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
              ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_cosmigo_user FOREIGN KEY (userId) REFERENCES User(userId)
);